language: python
python:
- '3.6'
before_install:
- if [[ -z $TRAVIS_TAG ]]; then sed -i "s/['\"]\([^\"]*\)['\"]/\"\1b$TRAVIS_BUILD_NUMBER\"/g"
  aws_ir_plugins/_version.py; fi
install:
- pip install -r requirements-dev.txt
- pip install flake8
- python -W ignore::UserWarning:distutils.dist setup.py build
script:
- flake8 plugins
- python setup.py test
deploy:
  - provider: pypi
    distributions: sdist bdist_wheel
    user: threatresponse
    password:
      secure: qYav6prhKwMUZX7ceFA0scfbDy/mobg1KQS3v507GqlYBhLX9y1LNy2j9tfDLPuEQFpirZ2wR2oIQOt6S1gnY8WGeoC242MlIIUCV+i0Rwi+zY7kEQxIeegkc37oqA0Xd3a+F9DlY0sVzS2PkScDj9CkQlAAUwfxvuZqIA6Eezaj325YTlmHOwc5WPsPW0CqrGpCz5Lu2B63Z+vvsH7/XVuO4K8qcTVaO+uosmY8tgVjwjNA/zsb8xvOsSfwgkphMVTPT94HjtgGLqWUqOkmcUh97dAEczf+0cRHNTJHd12kL2WlU1Zy5kP/GyqKpOwN57inOk408IFobGJKMCSdaKVBtsO+V4hs33IGuKHJdd0LwHyJqTwp7CTRwazxnK9InP7qrvMV1HhaupJrS5VtoOY4xw4MHzUpTM8kCaksZ3MSah/o7kIzTSPBR8Xh+ublPLaoTtTFXoH8d58GyLCU3JFvZdEXTi2ccdoKyQ6tI+J3Zi6Hig9xA/vQGij4aQNnPZiR7xOFKbUiunBhwcZ9EpwCSzw/ln/LmpAvQcsScIRaujzX2yJDWUI+91wR3EfYKGu3PrDIXu2ruICNyBY8wbJG7VOTxgzKVG4NunL/ylJWTs5f1lXh8bmomr7GOwNkjm0MjHV338UKukWlXrN+2M9ngBNK3+4TbWQbt6PqsiI=
    on:
      tags: true
  - provider: pypi
    server: https://test.pypi.org/legacy/
    distributions: sdist bdist_wheel
    user: threatresponse
    password:
      secure: gY6sH5lI7/dU6N/jegJOsbxyAJnpnF1+j5zs2fjwhCpg6MCR+Juzv+TzNKWxd8f8btq8QLLU6uOU+OG0CyUXbUIO5DcGg+iOi8Ec22Dywcng94BzMSvfzMaMbhk19bU35ePcnjmLmCiegxx1zs5YZKyI7unE3zMG7uSyv9f0a9J9TrdPk3kZtWvxd0vVY8KfAwuABrUlJauFmS+kfWYtLiXGamJmHT+IV6qyG3DP/Folv834xpD8LUSONdhHOLPtMqNEoZfwpYteICIixI2t8lzUYXGJFybrVlrhkQsgLfhuLiAutcvcP5bRUoWqr+3Vsz+xQqJ4V1ggUXrkMCA0XaqEm21aN7TVyoRazi1wc6AZPVIRy8+roW1t9S6otwCkP7ebaf7MfGGbjYX5eJV4Q6sw6LCS1NzJ7w72ms1c8YLN8JnfZu9NSYTQ9PhZDjN9jG15uKALD+5rp8ENbyHpGnqCu25FOO44RMgJavyBNw1p4fiGrkcgGF8xE4+D4XWrTfs1bDhmSPupAViRzGmhXPQw5oT5Kk/uTlwdEpQ1R3mILk20eMGywDl+nWY+z+I4RmAnDAwEnIW5jr+NNxaeYX/bT8gnKBclF8pKk7CZgr2CctuLIqdUEZlt160ZhUBzu9ijNXiz45Zs22Y+Pn7/fZ00YrMbWhGgrFLEERhirUU=
    skip_cleanup: true
    on:
      all_branches: true
