language: python
python:
- '3.6'
before_install:
- if [[ -z $TRAVIS_TAG ]]; then sed -i "s/['\"]\([^\"]*\)['\"]/\"\1b$TRAVIS_BUILD_NUMBER\"/g"
  aws_ir_plugins/_version.py; fi
install:
- pip install -r requirements-dev.txt
- pip install flake8
- python -W ignore::UserWarning:distutils.dist setup.py build
script:
- flake8 plugins
- python setup.py test
deploy:
  - provider: pypi
    distributions: sdist bdist_wheel
    user: threatresponse
    password:
      secure: qYav6prhKwMUZX7ceFA0scfbDy/mobg1KQS3v507GqlYBhLX9y1LNy2j9tfDLPuEQFpirZ2wR2oIQOt6S1gnY8WGeoC242MlIIUCV+i0Rwi+zY7kEQxIeegkc37oqA0Xd3a+F9DlY0sVzS2PkScDj9CkQlAAUwfxvuZqIA6Eezaj325YTlmHOwc5WPsPW0CqrGpCz5Lu2B63Z+vvsH7/XVuO4K8qcTVaO+uosmY8tgVjwjNA/zsb8xvOsSfwgkphMVTPT94HjtgGLqWUqOkmcUh97dAEczf+0cRHNTJHd12kL2WlU1Zy5kP/GyqKpOwN57inOk408IFobGJKMCSdaKVBtsO+V4hs33IGuKHJdd0LwHyJqTwp7CTRwazxnK9InP7qrvMV1HhaupJrS5VtoOY4xw4MHzUpTM8kCaksZ3MSah/o7kIzTSPBR8Xh+ublPLaoTtTFXoH8d58GyLCU3JFvZdEXTi2ccdoKyQ6tI+J3Zi6Hig9xA/vQGij4aQNnPZiR7xOFKbUiunBhwcZ9EpwCSzw/ln/LmpAvQcsScIRaujzX2yJDWUI+91wR3EfYKGu3PrDIXu2ruICNyBY8wbJG7VOTxgzKVG4NunL/ylJWTs5f1lXh8bmomr7GOwNkjm0MjHV338UKukWlXrN+2M9ngBNK3+4TbWQbt6PqsiI=
    on:
      tags: true
  - provider: pypi
    server: https://test.pypi.org/legacy/
    distributions: sdist bdist_wheel
    user: threatresponse
    password:
      secure: 3uOCHjL7ySENm8Wa7kYSgGJ1MyRH31nAyLbzT8MRSNW6ZmqlBhwe0GiaxVk6Iw1onaEBlCupLSiaYMw92FFA6jpAmtFQzQGk4jmiPu4u/lfrWhnWeOXruHrM1dkG4g3zxLDlpEA6m8maXc1sMZqp697Od8ID4FdhV9xLic8G0ahztSYo6yaVCmQXt0zT4bod8mZFutwgpdp80aPzQ1cYJkdv7f0ETBNrMoHZBjaLSbGWXZburG4xNbEQlDHAQAIZdiqR8rTtafhci4pAamYZpTrFT9yvczq1UmJWswbaiwRKBlAb9aRWXe3hTWWP+ffU2mRO0WDgQeUCbyNAoRo8dP6zLWtxtut5+abrRoFcPOxQwB7ATkFt/sKDmq6mJvuRDvHnOWGGVmqMTD+qpJO+e/BEGsDMR9SVRJw51UeQk5tMrQnHCPxoX1f7PB3cZItiIW92qlJQMtTHLaLZvWeqwfbODfwMw1gKMqNkvjKmqHBThCtpTg2A//bSQCV7ZERB5VWwLOfcUNFLM+tvGmQPk9zV3BXjcEBjBSa4wBVOOieijW164+FX273Zn/g/BZM0iloo5NMTchRV1sNpvFJIcDE0aLnlJnLXB2G/OsRLSG0WiTRLAtnHD5D0PYqzz4mmIlPrujkIRS4BnnHlwfbDQTgK8DDK4xd+InjZ5xjmkOw=
    skip_cleanup: true
    on:
      all_branches: true
